"""create tables

Revision ID: c575d3197255
Revises: a5081e27737a
Create Date: 2026-06-05 13:31:27.338128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c575d3197255'
down_revision: Union[str, Sequence[str], None] = 'a5081e27737a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pid', sa.CHAR(length=36), nullable=False))
    op.create_index(op.f('ix_users_pid'), 'users', ['pid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_pid'), table_name='users')
    op.drop_column('users', 'pid')
    # ### end Alembic commands ###
